apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: lakehouse
spec:
  accessModes:
    - ReadWriteOnce # O volume pode ser montado como leitura/escrita por um único nó
  resources:
    requests:
      storage: 10Gi # Pedimos 10 Gigabytes de espaço