apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-minio-write-test
  namespace: lakehouse
spec:
  type: Python
  mode: cluster

  image: "k8s-lakehouse/spark:3.5.6-v2"
  imagePullPolicy: IfNotPresent

  mainApplicationFile: local:///opt/spark/work-dir/app/test_minio_write.py
  sparkVersion: 3.5.6
  sparkConf:
    "spark.hadoop.fs.s3a.endpoint": "https://lakehouse-minio-hl.lakehouse.svc.cluster.local:9000"
    "spark.hadoop.fs.s3a.access.key": "minio" #"Ysh8lpSgpp9YO3oRLkkK"
    "spark.hadoop.fs.s3a.secret.key": "minio123" #"sSkln1c0sxRFT4hO24XRs1TfvVPys37VY5dGDJCq"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.hadoop.fs.s3a.connection.ssl.enabled": "false"
    "spark.hadoop.fs.sde.a.connection.ssl.certificate-check": "false" 
    "spark.hadoop.fs.s3a.connection.timeout": "30000"
    "spark.network.timeout": "40s"

  restartPolicy:
    type: Never
  
  driver:
    cores: 1
    memory: "512m"
    serviceAccount: spark-operator-spark
  
  executor:
    cores: 1
    instances: 2
    memory: "512m"